const fs = require('fs')
const lines = fs.readFileSync('script.rb', 'utf-8').split('\n')
/* eslint-disable quote-props */
const nametags = {
  '南條　輝正': 'Nanjo Terumasa',
  '右代宮　金蔵': 'Ushiromiya Kinzo',
  '呂ノ上　源次': 'Ronoue Genji',
  '右代宮　戦人': 'Ushiromiya Battler',
  '右代宮　譲治': 'Ushiromiya George',
  'ベアトリーチェ': 'Beatrice',
  'ベルンカステル': 'Bernkastel',
  '右代宮　絵羽': 'Ushiromiya Eva',
  '郷田　俊朗': 'Gohda Toshiro',
  '右代宮　秀吉': 'Ushiromiya Hideyoshi',
  '右代宮　朱志香': 'Ushiromiya Jessica',
  '嘉音': 'Kanon',
  '右代宮　霧江': 'Ushiromiya Kyrie',
  '右代宮　蔵臼': 'Ushiromiya Krauss',
  '熊沢　チヨ': 'Kumasawa Chiyo',
  '右代宮　真里亞': 'Ushiromiya Maria',
  '右代宮　夏妃': 'Ushiromiya Natsuhi',
  '右代宮　楼座': 'Ushiromiya Rosa',
  '右代宮　留弗夫': 'Ushiromiya Rudolf',
  '紗音': 'Shannon',
  'ラムダデルタ': 'Lambdadelta',
  'ルシファー': 'Lucifer',
  'レヴィアタン': 'Leviathan',
  'サタン': 'Satan',
  'ベルフェゴール': 'Belphegor',
  'マモン': 'Mammon',
  'ベルゼブブ': 'Beelzebub',
  'アスモデウス': 'Asmodeus',
  'ロノウェ': 'Ronove',
  'シエスタ４１０': 'Chiester410',
  'シエスタ４５': 'Chiester45',
  'シエスタ００': 'Chiester00',
  'シエスタ５５６': 'Chiester556',
  'さくたろう': 'Sakutarou',
  'ワルギリア': 'Virgilia',
  '天草　十三': 'Amakusa',
  '右代宮　縁寿': 'Ushiromiya Ange',
  '須磨寺　霞': 'Kasumi',
  '川畑船長': 'Kawabata',
  '南條　雅行': 'Masayuki',
  '小此木　鉄郎': 'Okonogi',
  '大月教授': 'Ootsuki',
  '熊沢　鯖吉': 'Sabakichi',
  '古戸　ヱリカ': 'Furudo Erika',
  'コーネリア': 'Cornelia',
  'ドラノール': 'Dlanor',
  'ガートルード': 'Gertrude',
  'フルフル': 'Furfur',
  'ゼパル': 'Zepar',
  'フェザリーヌ': 'Featherine',
  'ウィラード・Ｈ・ライト': 'Will',
  '右代宮　理御': ' Ushiromiya Lion',
  '山羊の従者': 'Goat',
  'ガァプ': 'Gaap',
  'エヴァ・ベアトリーチェ': 'EVA-Beatrice',
  '八城　十八': 'Tohya',
  '姉ベアトリーチェ': 'Ältere Beatrice',
  'クレル': 'Clair',
  'エンジェ・ベアトリーチェ': 'Ange-Beatrice',
  '八城　幾子': 'Ikuko',
  '寿ゆかり': 'Yukari',
  'サク': 'Saku',
  '黒き戦人': 'Dunkler Battler',
  'フラウロス': 'Flauros',
  'ピース': 'Piece',
  'ウェルギリアス': 'Virgilius'
}
/* eslint-enable quote-props */
for (let i = 0; i < lines.length; i++) {
  if (!lines[i].startsWith('s.ins 0x86')) continue
  for (const nt of Object.keys(nametags)) {
    lines[i] = lines[i].replace(`s.layout('${nt}@r`, `s.layout('${nametags[nt]}@r`)
  }
}
fs.writeFileSync('script.rb', lines.join('\n'), 'utf-8')
