name: Test build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
        
      - name: Build patch archives
        run: bash build.sh
        env:
          SKIP_ARCHIVE: 1
        
      - name: Upload Atmos build
        uses: actions/upload-artifact@v3
        with:
          name: patch_atmos
          path: mods
          
      - name: Create suyu subfolder
        run: |
          mkdir patch_suyu
          mv UminekoCatboxGerman patch_suyu/UminekoCatboxGerman
      
      - name: Upload suyu build
        uses: actions/upload-artifact@v3
        with:
          name: patch_suyu
          path: patch_suyu
